GET: http://localhost:3000
###
POST http://localhost:3000/user/resgister
Content-Type: application/json

{
    "email": "Huy002@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "Huy002@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZiOWU1ZmE4Yjc1YTRlZjA2ZmVmY2QiLCJpYXQiOjE3MTEwMTA4NTgsImV4cCI6MTcxMTYxNTY1OH0.BPPWq69TAXSIurmRa2jISrLyGWJylJDB3qoyO55sOh8"
}

###
GET http://localhost:3000/user/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZiOWU1ZmE4Yjc1YTRlZjA2ZmVmY2QiLCJpYXQiOjE3MTEwMDUxMjksImV4cCI6MTcxMTAwNTEzOX0.hi6jT55677f68TM3B0JMQkkltZqfI3xIfNnDrd43ZDA

###
POST http://localhost:3000/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZiOWU1ZmE4Yjc1YTRlZjA2ZmVmY2QiLCJpYXQiOjE3MTEwMTA4NTgsImV4cCI6MTcxMTYxNTY1OH0.BPPWq69TAXSIurmRa2jISrLyGWJylJDB3qoyO55sOh8"
}

###
POST http://localhost:3000/v1/api/user
Content-Type: application/json

{
    "userId": 3,
    "amount": 10
}


###
POST http://localhost:3000/v1/api/transfer
Content-Type: application/json

{
    "fromId": 1,
    "toId": 2,
    "amount": 30
}
